import { Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "./providers/SessionProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SaveToken from "@/components/SaveToken";
import { Toaster } from "sonner";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Nike",
  icons: {
    icon: "/assets/logo.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthSessionProvider>
          <Navbar />
          <Toaster position="top-center" />
          <SaveToken />
          {children}
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
